name: kube-ansbile

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/pipeline.yml'
      - 'main.py'
      - 'upload.json'
  schedule:
    - cron: '00 18 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup qiniu qshell environment
      uses: foxundermoon/setup-qshell@v1.0
      with:
        qshell-version: 2.4.2

    - name: Clean up disk space
      run: |
        set -x
        [ test -f /swapfile ] && sudo swapoff /swapfile
        [ test -f ] && sudo rm -rf /swapfile
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker rmi $(docker images -q)
        sudo apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php* \
          docker* \
          containerd*
        sudo apt autoremove --purge -y

    - name: Initialization environment
      run: |
        set -x
        sudo apt-get install python3 python3-pip tree -y
        sudo timedatectl set-timezone Asia/Shanghai

    - name: Download package
      run: |
        python3 ./main.py
        tree .

    - name: Sync to qiniu
      run: |
        qshell account ${{ secrets.AccessKey }} ${{ secrets.SecretKey }} default
        qshell qupload upload.json

    - name: Auto commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m 'auto commit'
        git push origin master